### ISSUE TITLE
not support multiple data types to return

### ISSUE THREAD

**Issue by HW140701** [metayeti/mINI#30]
now only support return std::string，

`std::string value = ini.get("section").get("key");`

but we want

`int value = ini.get("section").get("key").get<int>();`

**Comment by metayeti** [comment]
This is by design. To keep the library simple, I've decided early on to only work with std::string. It's not hard to write a wrapper that does what you want.

**Comment by MabelYT** [comment]
Hey @HW140701,
To Get An Int From It, Just Call It Like This:
```c++
std::string valueRaw = ini["section"]["key"];
// Handle Invalid Characters Here.
int Value = stoi(valueRaw);
```
