### ISSUE TITLE
error while using std::stoi with string from mINI.

### ISSUE THREAD

**Issue by Ogurrr** [metayeti/mINI#32]
Hi, 
I'm trying to use the int from the ini file but I can't because when I run it I get the message:
terminate called after throwing an instance of 'std::invalid_argument'
 what(): stands
Does anyone know how to fix this?
Thanks!

**Comment by rdanbrook** [comment]
You will need to make sure the string is not empty.

Here is a snippet where I am using this lib:
```
    for (const auto& setting : settings) {
        std::string& strval = ini[section][setting->name];

        if (strval.empty()) {
            continue;
        }

        int val = std::stoi(strval);
        if (val >= setting->min && val <= setting->max) {
            setting->val = val;
        }
    }
```
