### ISSUE TITLE
Read comments on the left of '=' as the value

### ISSUE THREAD

**Issue by SHM-white** [metayeti/mINI#37]
title

**Comment by metayeti** [comment]
Please provide a better description

**Comment by SHM-white** [comment]
The situation is same as [https://github.com/metayeti/mINI/issues/21](#21)
I'm sorry that I didn't see this when I open this issue. Now I have changed the code to support this situation
Additionally,is there any way to remain the comments when I want to save the ini file with another name and path?

**Comment by metayeti** [comment]
Yeah the comments work very specifically with this library. You cannot generate a non-existing file with comments. Your best bet would be writing a stub file with just empty values and all comments and formatting in place, and then writing to that same file with mINI.
