### ISSUE TITLE
Adding Comments to INI Files

### ISSUE THREAD

**Issue by aghaeifar** [metayeti/mINI#40]
Hi,

I am currently working with INI files and would like to know if it is possible to programmatically add comments to them. Specifically, I would like to include short descriptions for different sections within the file to improve readability.

**Comment by metayeti** [comment]
Hey. Nope, this is not possible with this library. The idea of this library is that there exists a pre-existing and pre-formated ini file which you write updates to. If generating a file with the library, it will always default to no comments. You can get around this by making your own INI file generator, and then you can use this library to write updates to it. That would we my approach, anyway. Basically as far as this library is concerned, comments don't really exist and they're merely skipped when reading or writing.

Hope that helps.
